name: Setup build tools and compile
description: Install dependencies, lint and build

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install Node.js v22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm run install

    - name: Lint
      shell: bash
      run: pnpm run lint

    - name: Build
      shell: bash
      run: pnpm run build
