name: build
description: Checkout, lint and build all packages
inputs:
  ref:
    description: GitHub branch reference to checkout
    type: string
    required: false

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Cache turbo build setup
      uses: actions/cache@v4
      with:
        path: .turbo
        key: ${{ runner.os }}-turbo-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-turbo-

    - name: Install Node.js v22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm run install

    - name: Lint
      run: pnpm run lint

    - name: Build
      run: pnpm run build

    # Without this, will get Error:
    # Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/coverage-badge-action/coverage-badge-action/action.yml'.
    # Did you forget to run actions/checkout before running your local action?
    - name: Checkout Back
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
