packages:
  - apps/*
  - packages/*
ignoredBuiltDependencies: null
onlyBuiltDependencies:
  - "@scarf/scarf"
  - "@sentry/cli"
  - bcrypt
  - cypress
  - esbuild
  - sharp
  - "true"
  - unrs-resolver
