name: Run CI
description: Runs Continuous Integration pipeline - lint, build, test

inputs:
  branch:
    description: The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event. Otherwise, uses the default branch.
    required: false

runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      ref: ${{ inputs.branch }}

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false

    - name: Install Node.js v22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install

    - name: Run linter
      run: pnpm run lint

    - name: Build and compile
      run: pnpm run build

    - name: Run tests and coverage
      run: pnpm run ci
