name: ci
description: Lint, build, and test

on: workflow_call

jobs:
  using: composite
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js v22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install dependencies, build and compile
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: pnpm run build

  lint:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Run linter
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Build and compile
        run: pnpm run build

  frontend-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run e2e tests
        run: pnpm run coverage:backend

  backend-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run api tests
        run: pnpm exec start-server-and-test "pnpm run start" "http-get://localhost:3000|http-get://localhost:3001" "pnpm run test:frontend"
