name: base-branch

on: workflow_call

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

  ci:
    uses: ./.github/workflows/ci.yml

  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Upload code coverage for ref branch
        uses: actions/upload-artifact@v4
        with:
          name: backend-ref-lcov.info
          path: packages/backend/coverage/lcov.info
          if-no-files-found: error
