name: Continuous Integration
description: Lint, build, and test
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Backend
        uses: ./.github/actions/tests/backend/
      - name: E2E
        uses: ./.github/actions/tests/e2e/
