name: ci
description: Lint, build, and test
permissions:
  contents: read
  pull-requests: write

on: workflow_call

jobs:
  install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Install Node.js v22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install dependencies, build and compile
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: pnpm run build

  lint:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Run linter
        run: pnpm run lint

  build:
    runs-on: ubuntu-latest
    needs: install-deps
    steps:
      - name: Build and compile
        run: pnpm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests and generate coverage reports
        run: pnpm run test
