name: ci
description: Lint, build, and test
permissions:
  contents: read
  pull-requests: write

on:
  workflow_call:
    inputs:
      ref:
        description: GitHub branch ref to run checks against
        type: string
        required: false

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/tests/backend.yml
        with:
          ref: ${{ github.base_ref }}

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/tests/e2e.yml
        with:
          ref: ${{ github.base_ref }}
