name: main

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js v22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run lint

      - name: Run backend tests and coverage
        run: pnpm run coverage:backend
      
      - name: Setup for Coverage Badge
        run: mkdir coverage && mv packages/backend/coverage/coverage-summary.json coverage/coverage-summary.json

      - name: Update Coverage Badge
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: we-cli/coverage-badge-action@main
