name: on-main
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ianyeoh/cooper/.github/workflows/ci.yml
    with:
      ref: ${{ github.base_ref }}
