name: main

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  ci:
    uses: ./.github/workflows/ci.yml

  publish-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Move backend coverage artifacts to root
        run: cp -R packages/backend/coverage/ coverage/

      - name: Upload coverage report to gh-pages
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: ./.github/actions/coverage-report
