name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js v22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run lint

      - name: Build and compile
        run: pnpm run build

      - name: Run tests and coverage
        run: pnpm run ci

      - name: Move backend coverage artifacts to root
        run: cp -R packages/backend/coverage/ coverage/

      - name: Upload coverage report to gh-pages
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: ./.github/actions/coverage-report
