name: ci

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      fail-fast: false

    steps:
      - name: Run CI
        uses: ./.github/actions/ci

      - name: Move backend coverage artifacts to root
        run: cp -R packages/backend/coverage/ coverage/

      - name: Upload coverage report to gh-pages
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: ./.github/actions/coverage-report
